spring:
  application:
    name: Munyeks-backend
  datasource:
    database:
      url: https://GEMINI_API_KEY/new key
        username: Munyeks
          password: 12345678
            driver-class-name:
  jpa:
    properties:
      hibernate:
        dialect: