spring:
  application:
    name: Munyeks-backend
  datasource:
    database:
      url:
        username:
          password:
            driver-class-name:
  jpa:
    properties:
      hibernate:
        dialect: